[package]
name = "material_core"
version = "0.1.0"
edition = "2024"

[dependencies]
material_lib = { path = "../material_lib" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"